import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const activationRequests = sqliteTable(
  "activation_requests",
  {
    id: text("id").primaryKey(),
    createdAt: text("created_at").notNull(),
    deadline: text("deadline").notNull(),
    activationDate: text("activation_date").notNull(),
    activationDay: text("activation_day").notNull().default(""),
    timeSlot: text("time_slot").notNull(),
    email: text("email").notNull().default(""),
    area: text("area").notNull(),
    regionScope: text("region_scope").notNull().default(""),
    vendorName: text("vendor_name").notNull(),
    accessMedia: text("access_media").notNull(),
    serviceType: text("service_type").notNull().default(""),
    workType: text("work_type").notNull().default(""),
    isRelocation: integer("is_relocation", { mode: "boolean" }).notNull().default(false),
    isRelayout: integer("is_relayout", { mode: "boolean" }).notNull().default(false),
    customerName: text("customer_name").notNull().default(""),
    customerContact: text("customer_contact").notNull().default(""),
    activationPic: text("activation_pic").notNull().default(""),
    siteId: text("site_id").notNull(),
    subsId: text("subs_id").notNull(),
    siteName: text("site_name").notNull().default(""),
    oppNumber: text("opp_number").notNull(),
    woNumber: text("wo_number").notNull(),
    devicePlan: text("device_plan").notNull(),
    installSwitch: integer("install_switch", { mode: "boolean" }).notNull().default(false),
    switchBrand: text("switch_brand").notNull().default(""),
    vlanSwitch: text("vlan_switch").notNull().default(""),
    switchPopPortAllocation: text("switch_pop_port_allocation").notNull().default(""),
    customerIp: text("customer_ip").notNull().default(""),
    buildType: text("build_type").notNull().default(""),
    buildDetail: text("build_detail").notNull().default(""),
    rfaCores: integer("rfa_cores").notNull(),
    popAllocation: text("pop_allocation").notNull(),
    popId: text("pop_id").notNull().default(""),
    popName: text("pop_name").notNull().default(""),
    cableLength: text("cable_length").notNull().default(""),
    cableType: text("cable_type").notNull().default(""),
    fatOdpCode: text("fat_odp_code").notNull().default(""),
    endToEnd: text("end_to_end").notNull().default(""),
    attenuation: text("attenuation").notNull().default(""),
    customerPort: text("customer_port").notNull().default(""),
    popOtbPort: text("pop_otb_port").notNull().default(""),
    odpFatPort: text("odp_fat_port").notNull().default(""),
    fatCoordinates: text("fat_coordinates").notNull().default(""),
    bandwidth: text("bandwidth").notNull().default(""),
    bandwidthIx: text("bandwidth_ix").notNull().default(""),
    bandwidthIix: text("bandwidth_iix").notNull().default(""),
    localLoop: text("local_loop").notNull().default(""),
    coordinationProof: text("coordination_proof").notNull().default(""),
    projectPic: text("project_pic").notNull(),
    vendorPic: text("vendor_pic").notNull(),
    provisioningPic: text("provisioning_pic").notNull(),
    status: text("status").notNull().default("Submitted"),
    completedAt: text("completed_at").notNull().default(""),
    pendingReason: text("pending_reason").notNull().default(""),
    rescheduleReason: text("reschedule_reason").notNull().default(""),
    picRescheduleReason: text("pic_reschedule_reason").notNull().default(""),
    picRescheduleDate: text("pic_reschedule_date").notNull().default(""),
    picRescheduleTimeSlot: text("pic_reschedule_time_slot").notNull().default(""),
    vendorRescheduleDate: text("vendor_reschedule_date").notNull().default(""),
    vendorRescheduleTimeSlot: text("vendor_reschedule_time_slot").notNull().default(""),
    rescheduleApprovalStatus: text("reschedule_approval_status").notNull().default(""),
    rescheduleRequestedBy: text("reschedule_requested_by").notNull().default(""),
    rescheduleOriginalStatus: text("reschedule_original_status").notNull().default(""),
    rescheduleApprovalReason: text("reschedule_approval_reason").notNull().default(""),
    rescheduleApprovedBy: text("reschedule_approved_by").notNull().default(""),
    rescheduleApprovedAt: text("reschedule_approved_at").notNull().default(""),
    requestType: text("request_type").notNull().default("Regular"),
    approvalStatus: text("approval_status").notNull().default("Not Required"),
    approvalCode: text("approval_code").notNull().default(""),
    approvedAt: text("approved_at").notNull().default(""),
    whatsappMessageId: text("whatsapp_message_id").notNull().default(""),
    notes: text("notes").notNull().default(""),
    screenshotUrl: text("screenshot_url").notNull().default(""),
  },
  (table) => [
    index("idx_activation_date_slot").on(table.activationDate, table.timeSlot),
    index("idx_activation_status").on(table.status),
    index("idx_activation_pic").on(table.provisioningPic),
    index("idx_activation_approval").on(table.approvalStatus, table.approvalCode),
  ],
);

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  username: text("username").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  salt: text("salt").notNull(),
  name: text("name").notNull(),
  role: text("role").notNull(),
  vendorName: text("vendor_name").notNull().default(""),
  regionScope: text("region_scope").notNull().default(""),
  createdAt: text("created_at").notNull(),
});
